
name: CICD-Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run
        run: |
          docker build -f Dockerfile.mysql -t ${{ secrets.DOCKER_USERNAME }}/mysql .
          docker build -f Dockerfile.laravel -t ${{ secrets.DOCKER_USERNAME }}/php-laravel .

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mysql
          docker push ${{ secrets.DOCKER_USERNAME }}/php-laravel

      - name: Test container
        run: |
          docker ps -a

  update_server:
    name: Updating prod environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker image pull ${{ secrets.DOCKER_USERNAME }}/mysql
            docker image pull ${{ secrets.DOCKER_USERNAME }}/php-laravel
            docker container stop mysql
            docker container stop php-laravel
            docker container prune -f
            docker run -d --network nginx-network --name mysql -p 3306:3306 ${{ secrets.DOCKER_USERNAME }}/mysql
            docker run -d --network nginx-network --name php-laravel --restart unless-stopped -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/php-laravel
            docker image prune -f
